apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.config.shop.port }}
