POST http://{{host}}:{{port}}/api/v1/shop/album
Cookie: on_demand_env={{owner}}

{
  "title": "title",
  "artist": "artist",
  "price": 77.7
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
