POST http://{{host}}:{{port}}/api/v1/shop/album

{
  "id": "de601b22-9f0d-11ee-88a9-de2ca0523ec3",
  "title": "title",
  "artist": "artist",
  "price": 77.7
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
