apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configuration
  labels:
    app: {{ .Values.name }}
data:
  POSTGRES_DB: "shop"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  init.sql: |
    {{ $.Files.Get "files/sql/init.sql" | indent 4 }}
