apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: {{ .Values.name }}
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Values.name }}
