name: CI - shop application

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gather runtime environment versions - asdf
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: go version

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -o ./bin/shop ./cmd

      - name: Run component tests
        run: |
          go test ./component-test/test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shop:latest
