name: CI - basic verification

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "CI - basic verification" ]
    types:
      - completed

permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gather runtime environment versions - asdf
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: go version

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -o ./bin/shop ./cmd

      - name: Run component tests
        run: |
          go test ./component-test/test
